server:
  port: ${PORT:8080}
  shutdown: graceful

logging:
  level[net.talaatharb.patientinformationbackend]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./db/${spring.application.name};AUTO_SERVER=TRUE;
    username: sa
    password:
  application:
    name: patient-information-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
