name: Java CI with Maven

on:
  push:
    branches:
      - '**'
    paths:
      - 'patient-information-backend/**'
      - '.github/workflows/maven-build.yml'
  pull_request:
    branches: [ master, develop, release/* ]

jobs:
  build:
    name: Build and test java projects
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd patient-information-backend && mvn clean compile verify package --file pom.xml
